name: main
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
